services:
  - type: web
    name: yillik-site
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn uni_yillik.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yillik-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "yillik.site,www.yillik.site"

databases:
  - name: yillik-db
    plan: free
